BlogUygulaması/Controllers/KonuController.cs
using Microsoft.AspNetCore.Mvc;
using BlogUygulaması.Models;
using Microsoft.EntityFrameworkCore;

namespace BlogUygulaması.Controllers;

public class KonuController : Controller
{
    private readonly DataContext _context;
    public KonuController(DataContext context)
    {
        _context = context;
    }

    public ActionResult Index()
    {
        var yazilar = _context.KonularModel.ToList();
        return View(yazilar);
    }

    public ActionResult Search()
    {
        return View();
    }

    public async Task<ActionResult> CategoryDetailsAsync(int Id)
    {

        var result = await _context.WordModels.Where(i => i.KonularId == Id).ToListAsync();

        ViewData["konuhead"] = await _context.KonularModel.Where(i => i.Id == Id).Select(k => k.Konu).FirstOrDefaultAsync();
        return View(result);
    }

}

BlogUygulaması/Controllers/LoginController.cs
using System.Threading.Tasks;
using BlogUygulaması.Models;
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BlogUygulaması.Controllers;

public class LoginController : Controller
{
    private readonly DataContext _context;
    private readonly UserManager<AppUser> _userManager;

    private SignInManager<AppUser> _signInManager;

    public LoginController(DataContext context, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
    {
        _context = context;
        _userManager = userManager;
        _signInManager = signInManager;
    }

    public ActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task<ActionResult> Index(AccountLoginModel model, string? returnUrl)
    {
        if (ModelState.IsValid)
        {
            var user = await _userManager.FindByEmailAsync(model.Email);

            if (user != null)
            {
                await _signInManager.SignOutAsync();

                var result = await _signInManager.PasswordSignInAsync(user, model.Password, model.BeniHatirla, true);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }

                else if (result.IsLockedOut)
                {
                    // GetLockoutEndDateAsync(user) bilgisi kullanıcının giriş için ne kadar sonra hesabının kitlendiği bilgisini bize söyler
                    var locoutDate = await _userManager.GetLockoutEndDateAsync(user);
                    var timeLeft = locoutDate.Value - DateTime.UtcNow;

                    ModelState.AddModelError("", $"Hesabınız Kitlenmiştir.Lütfen {timeLeft.Minutes + 1} dakika sonra tekrar deneyiniz.");
                }
            }
            else
            {
                ModelState.AddModelError("", "Böyle Bir Hesap Bulunmamaktadır");
            }
        }
        else
        {

        }
        return View(model);
    }


    public ActionResult Signin()
    {
        return View();
    }

    [HttpPost]
    public async Task<ActionResult> Signin(AppUserCreate model)
    {

        if (ModelState.IsValid)
        {
            var user = new AppUser
            {
                UserName = model.Email,
                AdSoyad = model.AdSoyad,
                Email = model.Email,
            };

            var result = await _userManager.CreateAsync(user, model.Password);

            if (result.Succeeded)
            {
                return RedirectToAction("Index", "Admin");
            }

            foreach (var error in result.Errors)
            { // Burada yaptığımız şey result.Errors değeri içerisinde çıkan hataları AddModelError değeri ModelState içerisine atmış oluruz error.Description değeri ile de gelen hataları yazdırırız.
                ModelState.AddModelError("", error.Description);
            }
        }
        return View(model);
    }

    public ActionResult AccessDenied()
    {
        return View();
    }

}

BlogUygulaması/Controllers/UserController.cs
using System.Threading.Tasks;
using BlogUygulaması.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogUygulaması.Controllers;

public class UserController : Controller
{
    private readonly DataContext _context;

    public UserController(DataContext context)
    {
        _context = context;
    }

    public async Task<ActionResult> Index()
    {
        return View();
    }

}

BlogUygulaması/Views/Shared/Partials/Site/_Footer.cshtml
@* <style>
    footer {
        margin-top: 180px;
    }
</style> *@

<footer class="mt-5 pt-5 pb-5 mb-0 p-4 bg-light text-center ">
    <div id="_footer">
        <p>© 2025 Çınar Özgürgil | Tüm hakları saklıdır.</p>
        <div>
            <a href="https://github.com/HunterLion2" target="_blank">GitHub</a> |
            <a href="https://linkedin.com/in/çınar-özgürgil-38319a225" target="_blank">LinkedIn</a>
        </div>
        <div>
            <a href="/privacy">Gizlilik Politikası</a> |
            <a href="/about">Hakkımda</a>
            <div class="version d-flex justify-content-end">Version 1.3.0</div>
        </div>
    </div>
</footer>

BlogUygulaması/Views/Shared/Partials/Site/_Topbar.cshtml
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=PT+Serif:ital,wght@0,400;0,700;1,400;1,700&display=swap"
        rel="stylesheet">
</head>

<nav class="navbar navbar-expand-lg " id="_topbar">
    <div class="container-fluid w-100">
        <button class="navbar-toggler m-2" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex flex-row justify-content-center w-100 p-5">
                <li class="nav-item px-4">
                    <a class="nav-link" asp-controller="Home" asp-action="Index" id="top-link">Anasayfa</a>
                </li>
                <li class="nav-item px-4">
                    <a class="nav-link" asp-controller="About" asp-action="Index" id="top-link">Hakkımda</a>
                </li>
                <li class="nav-item px-4">
                    <a class="nav-link" asp-controller="Konu" asp-action="Index" id="top-link">Konular</a>
                </li>
                @if (User != null)
                {
                    <li class="nav-item px-4">
                        <a asp-controller="Login" asp-action="Index" id="top-link"><i
                                class="fa-solid fa-circle-user fs-3"></i></a>
                    </li>
                }
                else
                {
                    <li class="nav-item px-4">
                        <a asp-controller="User" asp-action="Index" id="top-link"><i
                                class="fa-solid fa-circle-user fs-3"></i></a>
                    </li>
                }
            </ul>
        </div>
    </div>
</nav>